
#-----------------------------------------------------------------------
APP       := Base
TARGET    := HttpWupClient

CONFIG    := 
STRIP_FLAG:= N 

INCLUDE   += 
#LIB       += -lz 

#-----------------------------------------------------------------------

include /usr/local/tars/cpp/makefile/makefile.tars.new

