name: build-gateway-tag


on:
  push:
    tags:
      - v*

jobs:
  build:
    container: tarscloud/base-compiler-stretch:master
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.tarsyun.com
          username: ${{ secrets.name }}
          password: ${{ secrets.pass }}
      - name: Get version
        id: get_version
        run: echo "::set-output name=VERSION::${GITHUB_REF#refs/tags/}"
      - name: make
        run: mkdir -p build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release && make -j8
      - name: build docker
        run: exec-build-cloud.sh tarscloud/tars.cppbase cpp build/bin/GatewayServer yaml/gateway.yaml ${{ steps.get_version.outputs.VERSION }} true

