name: build-gateway-master

on:
  push:
    branches:
      - gateway-system
    paths:
      - "web/*"
      - "yaml/*"
jobs:
  build:
    container: tarscloud/base-compiler-stretch:master
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.tarsyun.com
          username: ${{ secrets.name }}
          password: ${{ secrets.pass }}
      - name: build gateway web docker
        run: |
          cd web/src; npm install; cd ../..
          exec-build-cloud.sh tarscloud/tars.nodejsbase nodejs web yaml/web.yaml latest true          
