name: build-gateway-master


on:
  push:
    branches:
      - master

jobs:
  build:
    container: tarscloud/base-compiler:v2.4
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.name }}
          password: ${{ secrets.pass }}
      - name: make
        run: mkdir -p build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release && make -j8
      - name: build docker
        run: exec-build.sh tarscloud/tars.cppbase cpp build/bin/GatewayServer yaml/values.yaml latest true

